# Name of the workflow
name: Zero2NN CI

# When should all the checks take place and changes on which all branches should trigger these tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Start with the Job Name and further mention all the tests you need to run
  test_micrograd:

    # Most common env
    runs-on: ubuntu-latest

    # Mention all the steps or checks that you want to perform
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Mention the python version that the repo should consider
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    # To install all the required dependecies -> mostly mentioned in requirements.txt 
    # nbconvert and nbformat are used to change the kernel required to run notebooks
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements.txt
        pip install nbconvert nbformat

    # Fix notebook kernel to avoid 'No such kernel named zero2nn'
    - name: Fix notebook kernel for GitHub Actions
      run: |
        python -c "
        import nbformat
        nb = nbformat.read('notebooks/micrograd_demo.ipynb', as_version=4)
        nb['metadata']['kernelspec']['name'] = 'python3'
        nb['metadata']['kernelspec']['display_name'] = 'Python 3'
        nbformat.write(nb, open('notebooks/micrograd_demo.ipynb', 'w'))"

    # Test to make sure that micrograd has been implemented successfully
    - name: Run notebook smoke tests
      run: |
        jupyter nbconvert --execute notebooks/micrograd_demo.ipynb --to notebook --stdout

    # Prints the final check once all the checks are completed
    - name: ✅ Finished
      run: echo "All checks passed!"
