name: Zero2NN CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.10]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements.txt
        pip install nbconvert nbformat

    # 🔧 Fix notebook kernel to avoid 'No such kernel named zero2nn'
    - name: Fix notebook kernel for GitHub Actions
      run: |
        python -c "
        import nbformat
        nb = nbformat.read('notebooks/micrograd_demo.ipynb', as_version=4)
        nb['metadata']['kernelspec']['name'] = 'python3'
        nb['metadata']['kernelspec']['display_name'] = 'Python 3'
        nbformat.write(nb, open('notebooks/micrograd_demo.ipynb', 'w'))"
    
    - name: Run notebook smoke tests
      run: |
        jupyter nbconvert --execute notebooks/micrograd_demo.ipynb --to notebook --stdout

    - name: ✅ Finished
      run: echo "All checks passed!"
